# syntax=docker/dockerfile:1

ARG base_image=edwardost/ubi8
ARG base_tag=8.9-1160
ARG qlik_tenant=obd
ARG qlik_user=qlik

FROM ${base_image}:${base_tag} AS gateway_instance

  ARG dnf_command
  ARG qlik_user
  ARG qlik_tenant

  ARG qlik_package=qlik-data-gateway-data-movement_2023.11-4_x86_64.rpm
  ARG qlik_package_version=2023.11-4
  ARG qlik_package_platform=x86_64

  ARG dnf_command=dnf

  LABEL maintainer="eost@qlik.com"
  LABEL qlik_package_version="${qlik_package_version}"
  LABEL qlik_package_platform="${qlik_package_platform}"
  LABEL qlik_tenant="${qlik_tenant}"

  ENV QLIK_TENANT=${qlik_tenant}
  ENV QLIK_PACKAGE_VERSION=${qlik_package_version}
  ENV QLIK_PACKAGE_PLATFORM=${qlik_package_platform}

  EXPOSE 3552/tcp

  ADD --chown=${qlik_user}:${qlik_user} "${qlik_package}" "${qlik_package}"
  COPY --chmod=740 --chown=${qlik_user}:${qlik_user} repagent-start.sh "./"

  RUN \
    sudo ${dnf_command} install -y python3 \
    && sudo QLIK_CUSTOMER_AGREEMENT_ACCEPT=yes QLIK_DMG_NO_SYSTEMD=yes rpm -ivh "${qlik_package}" \
    && cd /opt/qlik/gateway/movement/bin \
    && sudo ./agentctl qcs set_config --tenant_url "${qlik_tenant}.us.qlikcloud.com" \
    && cd /opt/qlik/gateway/movement/drivers/bin \
    && sudo ./install mysql -a \
    && sudo ./install postgres -a \
    && sudo ./install snowflake -a

  CMD [ "/home/qlik/repagent-start.sh" ]
