#!/usr/bin/env bash

qlik_data_movement_gateway_script_path=$(readlink -e "${BASH_SOURCE[0]}")
qlik_data_movement_gateway_script_dir="${qlik_data_movement_gateway_script_path%/*}"

# shellcheck source=qlik_data_movement_gateway.sh
source "${qlik_data_movement_gateway_script_dir}/qlik_data_movement_gateway.sh"

# shellcheck source=qlik_data_movement_gateway_config.sh
source "${qlik_data_movement_gateway_script_dir}/qlik_data_movement_gateway_config.sh"

# shellcheck source=qlik_data_movement_gateway_download.sh
source "${qlik_data_movement_gateway_script_dir}/qlik_data_movement_gateway_download.sh"

# shellcheck source=qlik_data_movement_gateway_build.sh
source "${qlik_data_movement_gateway_script_dir}/qlik_data_movement_gateway_build.sh"

# shellcheck source=qlik_data_movement_gateway_setup.sh
source "${qlik_data_movement_gateway_script_dir}/qlik_data_movement_gateway_setup.sh"

# shellcheck source=qlik_data_movement_gateway_shell.sh
source "${qlik_data_movement_gateway_script_dir}/qlik_data_movement_gateway_shell.sh"

# shellcheck source=qlik_data_movement_gateway_server.sh
source "${qlik_data_movement_gateway_script_dir}/qlik_data_movement_gateway_server.sh"

# shellcheck source=qlik_data_movement_gateway_start.sh
source "${qlik_data_movement_gateway_script_dir}/qlik_data_movement_gateway_start.sh"

# shellcheck source=qlik_data_movement_gateway_stop.sh
source "${qlik_data_movement_gateway_script_dir}/qlik_data_movement_gateway_stop.sh"
