#!/usr/bin/env bash

qlik_data_movement_gateway() {
  local qlik_data_movement_gateway_container_name="${qlik_data_movement_gateway_container_name:-qlik-data-movement-gateway}"
  local qlik_data_movement_gateway_volume="${qlik_data_movement_gateway_volume:-qlik-data-movement-gateway-data}"
  local qlik_data_movement_gateway_version="${qlik_data_movement_gateway_version:-23.1.3}"
  local qlik_data_movement_gateway_host_port="${qlik_data_movement_gateway_host_port:-9080}"
  local qlik_data_movement_gateway_container_port="${qlik_data_movement_gateway_container_port:-8978}"
  local qlik_data_movement_gateway_network="${qlik_data_movement_gateway_network:-mysql-network}"

  if [ $# -gt 0 ]; then
    case $1 in
      setup | server)
        set -- qlik_data_movement_gateway_"$1" "${@:2}"
      ;;
    esac
  fi

  "$@"
}
